### ISSUE TITLE
Techdocs not working as expected

### ISSUE THREAD

**Issue by geoffgibbs** [DiamondLightSource/developer-portal#104]
The documentation for this seems a little lacking, so this may be wrong on my end.

My attempt to provide techdocs is producing an embedded 404: https://dev-portal.diamond.ac.uk/catalog/default/component/uas-web-app/docs

**Comment by garryod** [comment]
Techdocs must be built in CI and published to our S3 bucket. This [how-to guide](https://diamondlightsource.github.io/developer-portal/user/how-tos/publish-a-techdocs-site/) should have what you need - the example GitLab workflow should be close to what you need. Let me know if you find anything to be unclear when  following it as you'll be the first real user

**Comment by geoffgibbs** [comment]
So, in the catalog, where shouild the techdocs ref point to?

**Comment by garryod** [comment]
As far as I'm aware it doesn't matter as the link is created from the S3 object to the entity, but convention is to point it to the directory the docs are built from (the one with the `mkdocs.yaml` file).

**Comment by geoffgibbs** [comment]
OK, I attempted a gitlab build similar to the one provided, unfortunately I get a fairly unhelp ful error and have no idea how to get more useful information out of the command line provided.

See: https://gitlab.diamond.ac.uk/uas/api-docs/-/jobs/133965
