### ISSUE TITLE
Catalog graph not working

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/developer-portal#636]
When opening the [URL](https://dev-portal.diamond.ac.uk/catalog-graph?maxDepth=40&unidirectional=true&mergeRelations=true&direction=LR&showFilters=true) nothing shows up.

Expected behavior: an interface to explore relations between services.

**Comment by garryod** [comment]
The page you have linked has no `rootEntityRefs` query parameter, thus the graph will not display anything. See: [the developer-portal-backend graph](https://dev-portal.diamond.ac.uk/catalog-graph?rootEntityRefs%5B%5D=component%3Adefault%2Fdeveloper-portal-backend&maxDepth=1) for a working example
