### ISSUE TITLE
Bug (?)- nested title/guide steps in the tree

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/developer-portal#677]
![image](https://github.com/DiamondLightSource/developer-portal/assets/56644812/f6ab731d-fc8c-4180-bb89-5453858b2ba0)

visible at url https://dev-portal.diamond.ac.uk/guide

**Comment by garryod** [comment]
This seems to be an issue with the [`developer-guide`](https://gitlab.diamond.ac.uk/sscc-docs/developer-guide) - could you see if you can reproduce it locally and raise an issue over there?

**Comment by stan-dot** [comment]
ok, will do

**Comment by stan-dot** [comment]
https://gitlab.diamond.ac.uk/sscc-docs/developer-guide/-/tree/main/docs/developer-portal/guide

I don't think it's the case.  mkdocs.yml treats this case differently
` nav:
  - Home: index.md
  - Policies:
    - ... | flat | policies/*.md
    - References:
      - ... | flat | policies/reference/*.md
  - Athena:
    - How Tos:
      - ... | flat | athena/how-tos/*.md
    - Explanations:
      - ... | flat | athena/explanations/*.md
  - AuthN/AuthZ:
    - Authentication:
      - How Tos:
        - ... | flat | authn-authz/authentication/how-tos/*.md
    - Authorization:
      - How Tos:
        - ... | flat | authz/docs/how-tos/*.md
      - Explanations:
        - ... | flat | authz/docs/explanations/*.md
      - References:
        - ... | flat | authz/docs/references/*.md
  - Containers:
    - Tutorials:
      - ... | flat | containers/tutorials/*.md
    - How Tos:
      - ... | flat | containers/how-tos/*.md
    - Explanations:
      - ... | flat | containers/explanations/*.md
  - Developer Portal:
    - Guide:
      - ... | developer-portal/guide/**
    - Catalog:
      - Tutorials:
        - ... | flat | developer-portal-catalog/docs/tutorials/*.md
      - How Tos:
        - ... | flat | developer-portal-catalog/docs/how-tos/*.md
      - Explanations:
        - ... | flat | developer-portal-catalog/docs/explanations/*.md
      - References:
        - ... | flat | developer-portal-catalog/docs/references/*.md`

**Comment by stan-dot** [comment]
this is solved with https://gitlab.diamond.ac.uk/sscc-docs/developer-guide/-/merge_requests/91
