### ISSUE TITLE
bug - broken link to the beamline plans page

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/developer-portal#678]
https://dev-portal.diamond.ac.uk/guide/athena/how-tos/migration/#beamline-plans-repository
source
and the real link:
 https://diamondlightsource.github.io/blueapi/main/how-to/write-plans.htm
 
 error link: https://diamondlightsource.github.io/blueapi/main/user/how-to/write-plans.htmll

**Comment by garryod** [comment]
This is also an issue with the `developer-guide` and should be raised there
