### ISSUE TITLE
Allow Groups to be imported, or define Groups

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/developer-portal#76]
https://github.com/DiamondLightSource/developer-portal/blob/db5c2d98314dbdee6b39a78c676332e4a3bdbbde/backstage/app-config.yaml#LL82C29-L82C29

Groups are default type of System.spec.owner and an allowed value for Service.spec.owner, and would be more accurate to use in some cases of either.

**Comment by garryod** [comment]
There is nothing stopping you defining a group with an entity descriptor at the moment. That being said, I would like to avoid this and instead import a set of groups from some centrally manged source, unfortunately I'm not aware of the existence of such a source at the moment, perhaps our linux groups would serve as the best proxy?

**Comment by ndevenish** [comment]
I don't think linux groups are fine-grained enough, and as far as I can tell, most people tend to katamari group labels additively until they leave; never having a group removed.

Probably the easiest way is to have some central place where Group (and customised user?) entities can be defined, which people can individually update - but with the condition that user mappings _must_ be resolvable against the source of truths for employee status; you want to be able to tell/alert when something becomes unowned, or a team becomes empty).

This might (?) be necessary anyway for some of the larger infrastructure components - I'm not sure there is a good single source of repository truth for the ISPyB database?
